# Generated by Django 4.1.1 on 2022-10-15 06:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_candidate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidate',
            name='profile_pic',
            field=models.ImageField(upload_to='app/image/candidate'),
        ),
    ]
