# Generated by Django 4.2.2 on 2023-06-16 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_alter_candidate_contact'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobpost',
            name='companycontact',
            field=models.IntegerField(max_length=10),
        ),
    ]
