# Generated by Django 4.2.2 on 2023-06-16 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_alter_jobpost_companycontact'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidate',
            name='contact',
            field=models.IntegerField(max_length=10, null=True),
        ),
    ]
