# Generated by Django 4.1.1 on 2022-10-15 07:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_alter_company_city_alter_company_user_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidate',
            name='user_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app.usermaster'),
        ),
    ]
