# Generated by Django 4.1.1 on 2022-10-15 07:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_candidate_user_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidate',
            name='user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.usermaster'),
        ),
    ]
