# Generated by Django 4.1.1 on 2022-10-22 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_alter_candidate_dob'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='logo_pic',
            field=models.ImageField(blank=True, null=True, upload_to='app/image/company'),
        ),
        migrations.AddField(
            model_name='company',
            name='state',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
