# Generated by Django 4.1.1 on 2022-10-22 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0015_alter_candidate_dob'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usermaster',
            name='otp',
            field=models.IntegerField(),
        ),
    ]
