# Generated by Django 4.1.1 on 2022-10-22 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0016_alter_usermaster_otp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidate',
            name='dob',
            field=models.CharField(max_length=50),
        ),
    ]
