# Generated by Django 4.1.1 on 2022-10-22 14:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0017_alter_candidate_dob'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='company',
            name='state',
        ),
    ]
