# Generated by Django 4.1.1 on 2022-10-22 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0018_remove_company_state'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usermaster',
            name='otp',
            field=models.CharField(max_length=5),
        ),
    ]
