# Generated by Django 4.1.1 on 2022-10-22 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0019_alter_usermaster_otp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usermaster',
            name='otp',
            field=models.IntegerField(),
        ),
    ]
