# Generated by Django 4.1.1 on 2022-10-22 15:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0020_alter_usermaster_otp'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='company',
            name='logo_pic',
        ),
    ]
