# Generated by Django 4.1.1 on 2022-10-22 15:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0021_remove_company_logo_pic'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usermaster',
            name='otp',
        ),
    ]
