# Generated by Django 4.1.1 on 2022-10-22 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0022_remove_usermaster_otp'),
    ]

    operations = [
        migrations.AddField(
            model_name='usermaster',
            name='otp',
            field=models.IntegerField(null=True),
        ),
    ]
