# Generated by Django 4.1.1 on 2022-10-23 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0024_alter_usermaster_otp'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='logo_pic',
            field=models.ImageField(blank=True, null=True, upload_to='app/image/company'),
        ),
    ]
