# Generated by Django 4.1.1 on 2022-10-23 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0026_remove_company_logo_pic'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='logo_pic',
            field=models.ImageField(blank=True, null=True, upload_to='app/image/company'),
        ),
    ]
