# Generated by Django 4.1.1 on 2022-10-23 14:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0027_company_logo_pic'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='company',
            name='logo_pic',
        ),
    ]
