# Generated by Django 4.1.1 on 2022-10-23 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0028_remove_company_logo_pic'),
    ]

    operations = [
        migrations.CreateModel(
            name='contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=20)),
                ('Eame', models.CharField(max_length=20)),
                ('Desc', models.CharField(max_length=20)),
            ],
        ),
        migrations.AddField(
            model_name='company',
            name='logo_pic',
            field=models.ImageField(blank=True, null=True, upload_to='app/image/company'),
        ),
    ]
