# Generated by Django 4.1.1 on 2022-11-09 02:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0029_contact_company_logo_pic'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='candidate',
            name='address',
        ),
        migrations.RemoveField(
            model_name='candidate',
            name='dob',
        ),
        migrations.RemoveField(
            model_name='candidate',
            name='gender',
        ),
        migrations.RemoveField(
            model_name='candidate',
            name='profile_pic',
        ),
    ]
