# Generated by Django 4.1.1 on 2022-11-09 02:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0031_applylist_jobpost_delete_contact'),
    ]

    operations = [
        migrations.CreateModel(
            name='contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40)),
                ('email', models.CharField(max_length=40, null=True)),
                ('subject', models.CharField(max_length=40)),
                ('message', models.CharField(default=False, max_length=200)),
            ],
        ),
    ]
