# Generated by Django 4.1.1 on 2022-12-05 06:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0032_contact'),
    ]

    operations = [
        migrations.CreateModel(
            name='Resume',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40, null=True)),
                ('email', models.CharField(max_length=40, null=True)),
                ('contact', models.CharField(max_length=12, null=True)),
                ('state', models.CharField(max_length=20, null=True)),
                ('city', models.CharField(max_length=20, null=True)),
                ('address', models.CharField(max_length=100, null=True)),
                ('skills', models.CharField(max_length=500, null=True)),
                ('education', models.CharField(max_length=500, null=True)),
                ('language', models.CharField(max_length=500, null=True)),
                ('summary', models.CharField(max_length=900, null=True)),
                ('linkedlink', models.FileField(upload_to='app/linkedlink')),
                ('cand_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.candidate')),
            ],
        ),
    ]
